ignore:
  - "src/test"
  - "src/main/java/cz/zcu/kiv/server/beecommunity/jpa"
  - "src/main/java/cz/zcu/kiv/server/beecommunity/controllers/api/v1"
  - "src/main/java/cz/zcu/kiv/server/beecommunity/BeeCommunityApplication.java"
  - "cz/zcu/kiv/server/beecommunity/jpa"
  - "cz/zcu/kiv/server/beecommunity/controllers"
  - "cz/zcu/kiv/server/beecommunity/BeeCommunityApplication.java"
  - "beecommunity/src/main/java/cz/zcu/kiv/server/beecommunity/jpa"
  - "beecommunity/src/main/java/cz/zcu/kiv/server/beecommunity/controllers/api/v1"
  - "beecommunity/src/main/java/cz/zcu/kiv/server/beecommunity/BeeCommunityApplication.java"
