services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=beecommunity_db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
      - 'TZ=Europe/Prague'
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - flyway

  flyway:
    image: flyway/flyway
    command:
      -url=jdbc:postgresql://10.:5432/beecommunity_db -schemas=public -user=admin -password=admin migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres